export const HOME_SCREEN_DATA = [
  {
    id: 1,
    title: 'Stothram',
    goto: 'ShotramScreen',
    darkBackground: '#878683',
    lightBackground: '#1abc9c',
    icon: 'database',
  },
  {
    id: 2,
    title: 'Bhajanas',
    goto: 'BhajaneScreen',
    darkBackground: '#878683',
    lightBackground: '#3498db',
    icon: 'profile',
  },
];

export const SHOTRAM_SCREEN_DATA = [
  {
    id: 1,
    title: 'Dashavatara',
    goto: 'Dashavatara',
    displayTitle: 'ದಶಾವತಾರ ಸ್ತೋತ್ರಂ',
  },
  {
    id: 2,
    title: 'GodaStuti',
    goto: 'GodaSthuti',
    displayTitle: 'ಗೋದಾ ಸ್ತುತಿಃ',
  },
  {
    id: 3,
    title: 'GopalaVimshathi',
    goto: 'GopalaVimshathi',
    displayTitle: 'ಗೋಪಾಲ ವಿಂಶತಿ',
  },
  {
    id: 4,
    title: 'Hayagriva',
    displayTitle: 'ಹಯಗ್ರೀವ ಸ್ತೋತ್ರಂ',
    goto: 'Hayagriva',
  },
  {
    id: 5,
    title: 'MukundaMala',
    displayTitle: 'ಮುಕುಂದಮಾಲಾ',
    goto: 'MukundaMala',
  },
  {
    id: 6,
    title: 'RaghuveeraGadya',
    displayTitle: ' ಶ್ರೀ ರಘುವೀರ ಗದ್ಯಂ',
    goto: 'RaghuveeraGadya',
  },
  {
    id: 7,
    title: 'Sudarshanastaka',
    displayTitle: 'ಶ್ರೀ ಸುದರ್ಶನ ಅಷ್ಟಕಂ',
    goto: 'Sudarshanastaka',
  },
  {
    id: 8,
    title: 'Tiruppavai',
    displayTitle: 'ತಿರುಪ್ಪಾವೈ',
    goto: 'Tiruppavai',
  },
  {
    id: 9,
    title: 'GarudaDandakam',
    displayTitle: 'ಶ್ರೀ ಗರುಡ ದಂಡಕಂ',
    goto: 'GarudaDandakam',
  },
  {
    id: 10,
    title: 'VishnuSahasranamam',
    displayTitle: 'ವಿಷ್ಣು ಸಹಸ್ರ ನಾಮ',
    goto: 'VishnuSahasranamam',
  },
  {
    id: 11,
    title: 'Jitante',
    displayTitle: 'ಜಿತಂತೇ ಸ್ತೋತ್ರಂ',
    goto: 'Jitante',
  },
  {
    id: 12,
    title: 'Nyasadashaka',
    displayTitle: 'ಶ್ರೀ ನ್ಯಾಸದಶಕಂ',
    goto: 'Nyasadashaka',
  },
  {
    id: 13,
    title: 'Amaladipiran',
    displayTitle: 'ಅಮಲನಾದಿಪಿರಾನ್',
    goto: 'Amaladipiran',
  },
  {
    id: 14,
    title: 'KanninunShiruttamb',
    displayTitle: 'ಕಣ್ಣಿನುಣ್ ಶಿರುತ್ತಾಮ್ಬು',
    goto: 'KanninunShiruttamb',
  },
  {
    id: 15,
    title: 'ChaturShloki',
    displayTitle: 'ಚತುಶ್ಲೋಕೀ',
    goto: 'ChaturShloki',
  },
  {
    id: 16,
    title: 'Tirupalland',
    displayTitle: 'ತಿರುಪ್ಪಲ್ಲಾಂಡು',
    goto: 'Tirupalland',
  },
  {
    id: 17,
    title: 'Tirupalliyucchi',
    displayTitle: 'ತಿರುಪ್ಪಳ್ಳಿಯೆಳುಚ್ಚಿ',
    goto: 'Tirupalliyucchi',
  },
  {
    id: 18,
    title: 'Shatumurai',
    displayTitle: 'ಶಾತ್ತುಮರೈ',
    goto: 'Shatumurai',
  },
  {
    id: 19,
    title: 'ShatumuraiValitirunam',
    displayTitle: 'ಶಾತ್ತುಮರೈ & ವಾಳಿತ್ತಿರುನಾಮಮ್',
    goto: 'ShatumuraiValitirunam',
  },
  {
    id: 20,
    title: 'DeshikaMangalam',
    displayTitle: 'ಶ್ರೀ ದೇಶಿಕಮಂಗಳಂ',
    goto: 'DeshikaMangalam',
  },
  {
    id: 21,
    title: 'SriStuti',
    displayTitle: 'ಶ್ರೀಸ್ತುತಿಃ',
    goto: 'SriStuti',
  },
  {
    id: 22,
    title: 'AdithyaHrudayam',
    displayTitle: 'ಆದಿತ್ಯ ಹೃದಯಮ್',
    goto: 'AdithyaHrudayam',
  },
  {
    id: 23,
    title: 'Ramaraksha',
    displayTitle: 'ಶ್ರೀ ರಾಮ ರಕ್ಷಾ ಸ್ತೋತ್ರಮ್',
    goto: 'Ramaraksha',
  },
];

export const BHAJANE_SCREEN_DATA = [
  {
    id: 1,
    title: 'BhajaYatirajam',
    displayTitle: 'ಭಜ ಯತಿರಾಜಂ',
    goto: 'BhajaYatirajam',
  },
  {
    id: 2,
    title: 'Thugire Rangana Thugire Krishnana',
    goto: 'ThugireRangana',
    displayTitle: 'ತೂಗಿರೆ ರಂಗನ',
  },
  {
    id: 3,
    title: 'Hanuman Chalisa',
    goto: 'HanumanChalisa',
    displayTitle: 'ಹನುಮಾನ್ ಚಾಲಿಸಾ',
  },
  {
    id: 4,
    title: 'Hare Krishna Mantram',
    goto: 'HareKrishnaMantram',
    displayTitle: 'ಹರೇ ಕೃಷ್ಣ ಮಂತ್ರಂ',
  },
  {
    id: 5,
    title: 'ShuddaBrahma',
    goto: 'ShuddaBrahma',
    displayTitle: 'ಶುದ್ಧಬ್ರಹ್ಮ',
  },
  {
    id: 6,
    title: 'Sreenivasa Neene Paliso',
    goto: 'SreenivasaNeenePaliso',
    displayTitle: 'ಶ್ರೀನಿವಾಸ ನೀನೇ',
  },
  {
    id: 7,
    title: 'Dheera Maruthi Gambeera Maruthi',
    goto: 'DheeraMaruthi',
    displayTitle: 'ಧೀರ ಮಾರುತಿ',
  },
  {
    id: 8,
    title: 'KodandaRama',
    goto: 'KodandaRama',
    displayTitle: 'ಕೋದಂಡರಾಮ',
  },
  {
    id: 9,
    title: 'SriramChandirane',
    goto: 'SriramChandirane',
    displayTitle: 'ಶ್ರೀ ರಾಮಚಂದಿರನೆ',
  },
];
